<?php
namespace App\Console\Commands;


use Laventure\Component\Console\Command\Command;
use Laventure\Component\Console\Input\Contract\InputInterface;
use Laventure\Component\Console\Output\Contract\OutputInterface;



/**
 * Class MakeUserCommand
 *
 * @package App\Console\Commands
 *
 * <Generated By Laventure 05/11/2022 11:49:31>
*/
class MakeUserCommand extends Command
{

    /**
     * @var string
    */
    protected $name = 'make:user';



    /**
     * @var string
    */
    protected $description = 'describe your command here...';




    /**
     * @param InputInterface $input
     * @param OutputInterface $output
     * @return int
    */
    public function execute(InputInterface $input, OutputInterface $output): int
    {
           // put your logic here

           $output->success('You are ready for execution make:user');

           return Command::SUCCESS;
    }
}