<?php
namespace App\Console\Commands;


use Laventure\Component\Console\Command\Command;
use Laventure\Component\Console\Input\Contract\InputInterface;
use Laventure\Component\Console\Output\Contract\OutputInterface;
use Laventure\Component\Console\Output\Table\ConsoleTable;


/**
 * Class TableCommand
 *
 * @package App\Console\Commands
 *
 * <Generated By Laventure 08/11/2022 21:42:39>
*/
class TableCommand extends Command
{

    /**
     * @var string
    */
    protected $defaultName = 'table';



    /**
     * @var string
    */
    protected $description = 'describe your command here...';




    /**
     * @param InputInterface $input
     * @param OutputInterface $output
     * @return int
    */
    public function execute(InputInterface $input, OutputInterface $output): int
    {
           // put your logic here

           $table = new ConsoleTable($output);

           $table->setHeaders([
              'ID', 'Name', 'Surname', 'Age', 'Address'
           ]);

           $table->setRows([
               [1, 'Name1', 'Surname1', '31', 'Moscow, golovinskoe shosse dom 1'],
               [2, 'Name2', 'Surname2', '32', 'Moscow, golovinskoe shosse dom 2'],
               [3, 'Name3', 'Surname3', '33', 'Moscow, golovinskoe shosse dom 3'],
               [4, 'Name4', 'Surname4', '34', 'Moscow, golovinskoe shosse dom 4'],
               [5, 'Name5', 'Surname5', '35', 'Moscow, golovinskoe shosse dom 5'],
               [6, 'Name6', 'Surname6', '36', 'Moscow, golovinskoe shosse dom 6'],
           ]);


           $table->render();

           // $output->success('You are ready for execution table');

           return Command::SUCCESS;
    }
}