<?php
namespace App\ORM\Mapper\Fixtures;


use Laventure\Component\Database\ORM\Mapper\Manager\EntityManager;
use Laventure\Component\Database\ORM\Mapper\Manager\Fixtures\Contract\Fixture;




/**
 * @class UserFixture
 *
 * @package App\ORM\Mapper\Fixtures
 *
 * <Generated By Laventure 06/11/2022 23:40:30>
*/
class UserFixture implements Fixture
{

      /**
       * @inheritDoc
      */
      public function load(EntityManager $manager)
      {
           // add your logic here
      }
}