<?php
namespace App\ORM\Mapper\Migrations;


use Laventure\Component\Database\Migration\Migration;
use Laventure\Foundation\Facade\Database\Schema;
use Laventure\Component\Database\Schema\BluePrint\BluePrint;


/**
 * @class Version20221103030610
 *
 * @package App\ORM\Mapper\Migrations
 *
 * <Generated By Laventure 03/11/2022 03:06:10>
*/
class Version20221103030610 extends Migration
{


    /**
      * @return void
    */
    public function up()
    {
        /*
        Schema::create('users', function (BluePrint $table) {
            $table->increments('id');
            // ...
        });
        */
    }


    /**
     * @return void
    */
    public function down()
    {
        // Schema::dropIfExists('users');
    }
}