<?php
namespace App\ORM\Model;

use Laventure\Component\Database\ORM\Model\Model;



/**
 * Class Dummy

 * @package App\ORM\Model
 *
 * <Generated By Laventure 06/11/2022 06:07:09>
*/
class Dummy extends Model
{

}