<?php
namespace App\ORM\Model;

use Laventure\Component\Database\ORM\Model\Model;



/**
 * Class User

 * @package App\ORM\Model
 *
 * <Generated By Laventure 03/11/2022 03:35:52>
*/
class User extends Model
{

}