<?php
namespace App\Http\Controllers;


use Laventure\Component\Http\Request\Request;
use Laventure\Component\Http\Response\Response;
use Laventure\Foundation\Http\Controllers\Controller;


/**
 * @class DemoController
 *
 * @package App\Http\Controllers
 *
 * <Generated By Laventure 02/11/2022 16:24:20>
*/
class DemoController extends Controller
{


        /**
         * @param Request $request
         * @return Response
        */
        public function index(Request $request): Response
        {
              return view('demo/index');
        }



        /**
         * @param $id
         * @return Response
        */
        public function show($id): Response
        {
              return view('demo/index');
        }



        /**
         * @return Response
        */
        public function create(): Response
        {
              return view('demo/create');
        }




        /**
         * @param Request $request
         * @return Response
        */
        public function store(Request $request): Response
        {
              return view('demo/store');
        }




        /**
         * @param Request $request
         * @param $id
         * @return Response
        */
        public function update(Request $request, $id): Response
        {
              return view('demo/index');
        }





        /**
         * @param $id
         * @return Response
        */
        public function destroy($id): Response
        {
              return view('demo/destroy');
        }


}